name: learning_sings
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  gif: ^2.3.0
  video_player: ^2.8.6
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  toasty_box: ^1.0.4
  cloud_firestore: ^4.15.8
  image_picker: ^1.0.8
  firebase_storage: ^11.6.9
  file_picker: ^8.0.0+1
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.0
  cached_network_image: ^3.3.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/gif/
    - assets/video/


  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
