// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5rT0U8ckLJ4onQP4jVAGBD2PkB1YWHWU',
    appId: '1:578610730081:web:61f50ba435c4f59b3dc620',
    messagingSenderId: '578610730081',
    projectId: 'learning-signs-2fd82',
    authDomain: 'learning-signs-2fd82.firebaseapp.com',
    storageBucket: 'learning-signs-2fd82.appspot.com',
    measurementId: 'G-RVZR1FBLGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwSVPzWRt43j3i-3lVALibTi9JTE29pnQ',
    appId: '1:578610730081:android:fb5d71448537dabf3dc620',
    messagingSenderId: '578610730081',
    projectId: 'learning-signs-2fd82',
    storageBucket: 'learning-signs-2fd82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXsrenBzSplsj7siwI7r2QzhbW5CBqTxc',
    appId: '1:578610730081:ios:fdc5a493c5ad16523dc620',
    messagingSenderId: '578610730081',
    projectId: 'learning-signs-2fd82',
    storageBucket: 'learning-signs-2fd82.appspot.com',
    iosBundleId: 'com.example.learningSings',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXsrenBzSplsj7siwI7r2QzhbW5CBqTxc',
    appId: '1:578610730081:ios:fdc5a493c5ad16523dc620',
    messagingSenderId: '578610730081',
    projectId: 'learning-signs-2fd82',
    storageBucket: 'learning-signs-2fd82.appspot.com',
    iosBundleId: 'com.example.learningSings',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5rT0U8ckLJ4onQP4jVAGBD2PkB1YWHWU',
    appId: '1:578610730081:web:8f95e7c96437aadb3dc620',
    messagingSenderId: '578610730081',
    projectId: 'learning-signs-2fd82',
    authDomain: 'learning-signs-2fd82.firebaseapp.com',
    storageBucket: 'learning-signs-2fd82.appspot.com',
    measurementId: 'G-0V3D19Z364',
  );
}
